name: drupal9
recipe: drupal9
config:
  via: apache
  php: '7.4'
  webroot: web/
  drush: ^10
  config:
    php: automation/docker-utils/php/php.ini
tooling:
  "lint:php:themes":
    service: appserver
    cmd: "composer phpcs:themes"
    description: "Runs php linter against your custom code. Ex: lando lint:php:themes"
  "lint:php:themes:fix":
    service: appserver
    cmd: "composer phpcbf:themes"
    description: "Fixes php linter against your custom code. Ex: lando lint:php:themes:fix"
  "lint:php:modules":
    service: appserver
    cmd: "composer phpcs:modules"
    description: "Runs php linter against your custom code. Ex: lando lint:php:modules"
  "lint:php:modules:fix":
    service: appserver
    cmd: "composer phpcbf:modules"
    description: "Fixes php linter against your custom code. Ex: lando lint:php:modules:fix"
  "deprecated:modules":
    service: appserver
    cmd: "composer deprecated:modules"
    description: "Check Drupal modules code for deprecations and discover bugs via static analysis."
  "deprecated:themes":
    service: appserver
    cmd: "composer deprecated:themes"
    description: "Check Drupal themes code for deprecations and discover bugs via static analysis."
  "phunit:modules":
    service: appserver
    cmd: "composer phunit:modules"
    description: "Run PHPUnit tests on a Drupal modules."
  "lint:scss":
    service: node
    cmd: "npm run lint:scss:themes"
    description: "Runs scss linter against your custom code. Ex: lando lint:scss"
  "lint:js":
    service: node
    cmd: "npm run lint:js:themes"
    description: "Runs js linter against your custom code. Ex: lando lint:js"
  "compile:scss":
    service: node
    cmd: "gulp -f=gulp.js"
    description: "Converts scss to css. Ex: lando compile:scss <themes/watchthemes>"
  "npm":
    service: node
    cmd: "npm"
    description: "Runs npm for installing or removing modules. Ex: lando npm <yourcommand>"
proxy:
  appserver:
    - drupal9.lndo.site
services:
  node:
    type: node:14
    build:
      - npm install
    globals:
      gulp-cli: latest
  appserver:
    build:
      - "cd /app && composer install"
      - "/app/vendor/bin/phpcs --config-set installed_paths /app/vendor/drupal/coder/coder_sniffer"
  drupal9:
    type: mysql:5.7
    portforward: true
    config:
      confd: lando/mysql/conf.d
